import type { MapDef } from "./types";

export const MAX_ENERGY = 200;
export const ENERGY_REGEN_PER_SEC = 5;
export const SAVE_VERSION = 2;
export const SAVE_KEY = "chillverse-save-v1";

export const TIER_COLORS: Record<string, string> = {
  I: "#3ecf8e",
  II: "#4f8ef7",
  III: "#9b6dff",
  IV: "#f5c542",
};

export const MAPS: MapDef[] = [
  {
    id: 1,
    name: "Greenfields",
    tier: "I",
    xpRequired: 0,
    style: "meadow",
    color: "#3ecf8e",
    blurb: "Moss roads, old gates, and a forest that still remembers names.",
    portrait: "/regions/greenfields.jpg",
    shrine: "/sprites/shrine-meadow.png",
    entry: { x: 6, y: 92 },
    chambers: [
      {
        id: 1,
        name: "Mossy Gate",
        baseTimeHours: 5,
        xpReward: 70,
        artifact: false,
        energyCost: 30,
        x: 18,
        y: 82,
        lore: "The first lintel is carved with a walking song. Pass through and the meadow opens.",
        relicName: "Gateleaf Charm",
        relicIcon: 1,
      },
      {
        id: 2,
        name: "Thornwood Pass",
        baseTimeHours: 5,
        xpReward: 110,
        artifact: true,
        energyCost: 40,
        x: 33,
        y: 56,
        lore: "Briars part for anyone who pays attention. A thornwood charm waits in the thicket.",
        relicName: "Thornwood Charm",
        relicIcon: 2,
      },
      {
        id: 3,
        name: "Sunken Altar",
        baseTimeHours: 5,
        xpReward: 180,
        artifact: false,
        energyCost: 50,
        x: 59,
        y: 70,
        lore: "Rainwater pools in the old bowl. Offer a minute of quiet and the stones answer.",
        relicName: "Sunken Tablet",
        relicIcon: 3,
      },
      {
        id: 4,
        name: "Root Labyrinth",
        baseTimeHours: 5,
        xpReward: 260,
        artifact: true,
        energyCost: 60,
        x: 71,
        y: 42,
        lore: "Roots braid into corridors. Follow the warm ones; they lead toward the hollow.",
        relicName: "Living Root Crystal",
        relicIcon: 4,
      },
      {
        id: 5,
        name: "The Deep Hollow",
        baseTimeHours: 5,
        xpReward: 550,
        artifact: true,
        energyCost: 80,
        x: 47,
        y: 19,
        lore: "A seed the size of a heart rests in the last chamber, humming like a held breath.",
        relicName: "Hollow Seed",
        relicIcon: 5,
      },
    ],
  },
  {
    id: 2,
    name: "Crystal Lake",
    tier: "II",
    xpRequired: 1000,
    style: "lakeside",
    color: "#4f8ef7",
    blurb: "Glass water, cinder halls, and a keep that still smokes at dusk.",
    portrait: "/regions/crystal-lake.jpg",
    shrine: "/sprites/shrine-lake.png",
    entry: { x: 5, y: 58 },
    chambers: [
      {
        id: 1,
        name: "Ember Arch",
        baseTimeHours: 5,
        xpReward: 400,
        artifact: false,
        energyCost: 45,
        x: 16,
        y: 71,
        lore: "Warm stone frames the lake road. Sparks cling to the arch long after sunset.",
        relicName: "Ember Shard",
        relicIcon: 6,
      },
      {
        id: 2,
        name: "Cinder Hall",
        baseTimeHours: 5,
        xpReward: 650,
        artifact: true,
        energyCost: 55,
        x: 33,
        y: 84,
        lore: "Ash carpets the floor in deliberate patterns. Someone still tends this hall.",
        relicName: "Cinder Mask",
        relicIcon: 7,
      },
      {
        id: 3,
        name: "Obsidian Court",
        baseTimeHours: 5,
        xpReward: 900,
        artifact: false,
        energyCost: 70,
        x: 53,
        y: 61,
        lore: "Black glass benches face the water. Sit and the lake shows a second sky.",
        relicName: "Obsidian Tear",
        relicIcon: 8,
      },
      {
        id: 4,
        name: "The Ashen Keep",
        baseTimeHours: 5,
        xpReward: 1200,
        artifact: false,
        energyCost: 85,
        x: 76,
        y: 68,
        lore: "Towers of cooled magma. The inner stair still holds heat like a secret.",
        relicName: "Keep Cinder",
        relicIcon: 6,
      },
      {
        id: 5,
        name: "Pyroclast Vault",
        baseTimeHours: 5,
        xpReward: 2500,
        artifact: true,
        energyCost: 110,
        x: 64,
        y: 24,
        lore: "The vault door is a cooled wave of stone. Inside, a core still ticks with fire.",
        relicName: "Pyroclast Core",
        relicIcon: 9,
      },
    ],
  },
  {
    id: 3,
    name: "Under World",
    tier: "III",
    xpRequired: 6500,
    style: "cavern",
    color: "#9b6dff",
    blurb: "Salt air underground, kelp-dark tunnels, a throne the sea forgot.",
    portrait: "/regions/under-world.jpg",
    shrine: "/sprites/shrine-cavern.png",
    entry: { x: 8, y: 94 },
    chambers: [
      {
        id: 1,
        name: "Salt Shore",
        baseTimeHours: 5,
        xpReward: 1200,
        artifact: false,
        energyCost: 60,
        x: 21,
        y: 85,
        lore: "A beach with no sky. Salt crystals grow in the shape of old waves.",
        relicName: "Saltglass Amulet",
        relicIcon: 1,
      },
      {
        id: 2,
        name: "Kelp Maze",
        baseTimeHours: 5,
        xpReward: 2000,
        artifact: true,
        energyCost: 75,
        x: 41,
        y: 69,
        lore: "Fronds hang where trees should be. Follow the biolume or walk in circles.",
        relicName: "Kelp Lantern Seed",
        relicIcon: 5,
      },
      {
        id: 3,
        name: "Drowned Citadel",
        baseTimeHours: 5,
        xpReward: 3500,
        artifact: false,
        energyCost: 90,
        x: 25,
        y: 42,
        lore: "Banners of algae mark a court that voted to stay below.",
        relicName: "Citadel Tablet",
        relicIcon: 3,
      },
      {
        id: 4,
        name: "Abyss Gate",
        baseTimeHours: 5,
        xpReward: 6000,
        artifact: true,
        energyCost: 110,
        x: 57,
        y: 33,
        lore: "The gate is a mouth of dark water standing upright. It only opens for the patient.",
        relicName: "Abyss Tear",
        relicIcon: 8,
      },
      {
        id: 5,
        name: "The Sunken Throne",
        baseTimeHours: 5,
        xpReward: 9000,
        artifact: false,
        energyCost: 140,
        x: 79,
        y: 17,
        lore: "An empty chair of coral and ore. Sit and the cavern listens.",
        relicName: "Throne Ore",
        relicIcon: 4,
      },
    ],
  },
  {
    id: 4,
    name: "The Void",
    tier: "IV",
    xpRequired: 20000,
    style: "space",
    color: "#f5c542",
    blurb: "No ground. Only platforms, star-dust, and a road that should not exist.",
    portrait: "/regions/the-void.jpg",
    shrine: "/sprites/shrine-void.png",
    entry: { x: 10, y: 92 },
    chambers: [
      {
        id: 1,
        name: "Cloud Vestibule",
        baseTimeHours: 5,
        xpReward: 3000,
        artifact: false,
        energyCost: 80,
        x: 25,
        y: 79,
        lore: "A waiting room of mist and gravity. Your footsteps make no sound here.",
        relicName: "Vestibule Spark",
        relicIcon: 6,
      },
      {
        id: 2,
        name: "Star Corridor",
        baseTimeHours: 5,
        xpReward: 5000,
        artifact: true,
        energyCost: 95,
        x: 47,
        y: 73,
        lore: "Constellations hang at arm's length. One of them is a key.",
        relicName: "Star Corridor Charm",
        relicIcon: 2,
      },
      {
        id: 3,
        name: "Void Sanctum",
        baseTimeHours: 5,
        xpReward: 8000,
        artifact: true,
        energyCost: 115,
        x: 37,
        y: 49,
        lore: "Silence with architecture. The walls are the idea of walls.",
        relicName: "Sanctum Mask",
        relicIcon: 7,
      },
      {
        id: 4,
        name: "Ether Pinnacle",
        baseTimeHours: 5,
        xpReward: 11000,
        artifact: true,
        energyCost: 140,
        x: 63,
        y: 39,
        lore: "The highest stone in a place without up. Wind that is not wind.",
        relicName: "Ether Core",
        relicIcon: 9,
      },
      {
        id: 5,
        name: "The Apex",
        baseTimeHours: 5,
        xpReward: 15000,
        artifact: true,
        energyCost: 175,
        x: 51,
        y: 15,
        lore: "The last map. From here every region is a story you already walked.",
        relicName: "Apex Relic",
        relicIcon: 8,
      },
    ],
  },
];

export function getMap(id: number): MapDef {
  return MAPS.find((m) => m.id === id) ?? MAPS[0]!;
}

export function expeditionDurationMs(energyCost: number): number {
  return Math.round(5200 + energyCost * 70);
}

export function isReachable(
  chambers: MapDef["chambers"],
  index: number,
  states: Record<string, ChamberStateLike>,
): boolean {
  if (index === 0) return true;
  const prev = chambers[index - 1];
  return prev ? states[String(prev.id)]?.status === "done" : false;
}

type ChamberStateLike = { status?: string } | undefined;

export function clearedCount(map: MapDef, states: Record<string, ChamberStateLike>): number {
  return map.chambers.filter((c) => states[String(c.id)]?.status === "done").length;
}
